name: Frontpage Release

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build:
    name: Build CV
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Change Directory to cv
        run: cd cv

      - name: Build CV With xelatex in Makefile in 
        run: make

      - name: Move CV to frontpage/
        run: mv /cv/src/kiersz-cv.pdf /frontpage/kiersz-cv.pdf

      - name: Upload an CV Arfifact
        uses: actions/upload-artifact@v3
        with:
          name: kiersz-cv
          path: /frontpage/kiersz-cv.pdf

      - name: Upload a Frontpage with CV Arfifact
        uses: actions/upload-artifact@v3
        with:
          name: kiersz-cv
          path: /frontpage/

  deploy:
    name: Deploy Frontpage and CV
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/production' && github.event_name == 'push'
    steps:
      - name: Download Frontpage with CV Artifact
        uses: actions/download-artifact@v2
        with:
          name: frontpage-cv
          path: ./frontpage
      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.PORKBUN_FTP_HOSTNAME }}
          username: ${{ secrets.PORKBUN_FTP_USERNAME }}
          password: ${{ secrets.PORKBUN_FTP_PASSWORD }}
          local-dir: ./frontpage
          server-dir: /frontpage