name: Frontpage Release

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build:
    name: Job - Build CV
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Build CV With xelatex in Makefile
        run: make
        working-directory: ./cv

      - name: Move CV to frontpage/
        run: mv /cv/src/kiersz-cv.pdf /frontpage/kiersz-cv.pdf

      - name: Upload Artifact - CV
        uses: actions/upload-artifact@v3
        with:
          name: kiersz-cv
          path: /frontpage/kiersz-cv.pdf

      - name: Upload Arfifact - Frontpage with CV 
        uses: actions/upload-artifact@v3
        with:
          name: kiersz-cv
          path: /frontpage/

  deploy:
    name: Job - Deploy Frontpage and CV
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/production' && github.event_name == 'push'
    steps:
      - name: Download Arfifact - Frontpage with CV
        uses: actions/download-artifact@v2
        with:
          name: frontpage-cv
          path: ./frontpage
      - name: FTP - Deploy Frontpage
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.PORKBUN_FTP_HOSTNAME }}
          username: ${{ secrets.PORKBUN_FTP_USERNAME }}
          password: ${{ secrets.PORKBUN_FTP_PASSWORD }}
          local-dir: ./frontpage
          server-dir: /frontpage