name: frontpage-release

# push on any branch
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
    
jobs:
  build:
    name: Job - Build CV
    runs-on: ubuntu-22.04
    container: texlive/texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Build CV With xelatex in Makefile
        run: make
        working-directory: ./cv

      - name: Move CV to frontpage/
        run: mkdir -p frontpage/cv && mv cv/src/kiersz-cv.pdf frontpage/cv/kiersz-cv.pdf

      - name: Upload Artifact - CV
        uses: actions/upload-artifact@v65462800fd760344b1a7b4382951275a0abb4808
        with:
          name: kiersz-cv
          path: frontpage/cv/kiersz-cv.pdf

      - name: Upload Arfifact - Frontpage with CV 
        uses: actions/upload-artifact@v65462800fd760344b1a7b4382951275a0abb4808
        with:
          name: frontpage-cv
          path: frontpage/

  deploy:
    name: Job - Deploy Frontpage and CV
    runs-on: ubuntu-22.04
    needs: build
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && github.event.action != 'closed')
    steps:
      - name: Download Arfifact - Frontpage with CV
        uses: actions/download-artifact@v65a9edc5881444af0b9093a5e628f2fe47ea3b2e
        with:
          name: frontpage-cv
          path: ${{ github.repository }}/frontpage
      - name: Deploy - Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@vc514ae36604047560e33605b78f71804967bfb7a
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "${{ github.repository }}/frontpage"
          output_location: ""
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          skip_app_build: true

  close_pull_request_job:
    name: Job - Close Pull Request Job
    runs-on: ubuntu-22.04
    needs: build
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@vc514ae36604047560e33605b78f71804967bfb7a
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"